# Generated by Django 4.0.1 on 2022-02-11 12:06

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import mcq_mlt.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(help_text='Enter the category name like: Loksewa, License, Entrance', max_length=75)),
                ('category_description', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(help_text='Enter the course name like: Lab Assistant, CMLT, BMLT', max_length=75)),
                ('course_description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, default='', max_length=100, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelset_title', models.CharField(help_text='Enter the Modelset name like: February First Week - BMLT Assistant Entrance', max_length=75)),
                ('active', models.BooleanField(default=False)),
                ('weightage', models.IntegerField(help_text='give questions of this modelset a point.', validators=[mcq_mlt.validators.validate_weightage])),
                ('hour', models.CharField(help_text='write 01, 02, or 03 like numbers only', max_length=75)),
                ('minutes', models.CharField(help_text='write 01, 02, or 03 like numbers only', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_statement', ckeditor.fields.RichTextField()),
                ('choice_1', ckeditor.fields.RichTextField()),
                ('choice_2', ckeditor.fields.RichTextField()),
                ('choice_3', ckeditor.fields.RichTextField()),
                ('choice_4', ckeditor.fields.RichTextField()),
                ('answer', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], default='option1', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syllabus_title', models.CharField(max_length=75)),
                ('syllabus_file', models.FileField(upload_to='syllabus_pdf')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.course')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('markes_obtained', models.IntegerField()),
                ('correct', models.IntegerField(null=True)),
                ('wrong', models.IntegerField(null=True)),
                ('unanswered', models.IntegerField(null=True)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('modelset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.modelset')),
            ],
        ),
    ]
