# Generated by Django 4.0.1 on 2022-02-17 07:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QOTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qotd_statement', ckeditor.fields.RichTextField()),
                ('answer', models.CharField(default='', max_length=75)),
            ],
        ),
    ]
