# Generated by Django 4.0.1 on 2022-02-17 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_qotd'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Level', 'verbose_name_plural': 'Levels'},
        ),
    ]
