# Generated by Django 4.0.1 on 2022-02-17 10:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_course_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='category',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_file',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabus',
            field=models.FileField(default=1, upload_to='syllabus_files'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_description',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_title',
            field=models.CharField(help_text='Enter the syllabus name like: Loksewa Syllabus - Province I', max_length=75),
        ),
    ]
