# Generated by Django 4.0.1 on 2022-02-17 12:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_syllabus_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='explanation',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
