# Generated by Django 4.0.1 on 2022-02-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_syllabus_syllabus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='syllabus_image',
        ),
    ]
