# Generated by Django 4.0.1 on 2022-02-22 02:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_remove_syllabus_syllabus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
