# Generated by Django 4.0.1 on 2022-03-06 09:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_syllabus_syllabus_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesyllabus',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus_description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
