# Generated by Django 4.0.1 on 2022-03-09 08:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_syllabus_syllabus_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='qotd',
            name='op_1',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='qotd',
            name='op_2',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='qotd',
            name='op_3',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='qotd',
            name='op_4',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
