# Generated by Django 4.0.1 on 2022-03-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_qotd_op_1_qotd_op_2_qotd_op_3_qotd_op_4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qotd',
            name='answer',
            field=models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], default='option1', max_length=75),
        ),
    ]
