# Generated by Django 4.0.1 on 2022-03-09 10:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0019_alter_qotd_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='qotd',
            name='explanation',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
