# Generated by Django 4.0.1 on 2022-03-13 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0020_qotd_explanation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelset',
            name='minutes',
            field=models.CharField(default='00', help_text='write 01, 02, or 03 like numbers only', max_length=75),
        ),
        migrations.CreateModel(
            name='QuizGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('modelset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz.modelset')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
