# Generated by Django 4.0.1 on 2022-03-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0022_coursesyllabus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelset',
            name='free',
            field=models.BooleanField(default=False),
        ),
    ]
