# Generated by Django 4.0.1 on 2022-03-24 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0024_studentgroup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='group_users',
            new_name='users',
        ),
    ]
