# Generated by Django 4.0.1 on 2022-03-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_rename_group_users_studentgroup_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgroup',
            name='allow_students',
            field=models.BooleanField(default=True),
        ),
    ]
