# Generated by Django 4.0.1 on 2022-04-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        ('quiz', '0028_modelset_minutes_alter_modelset_hour'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizgroup',
            name='social_auth_users',
            field=models.ManyToManyField(to='account.EmailAddress'),
        ),
    ]
