# Generated by Django 4.0.1 on 2022-03-15 06:01

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('content', ckeditor.fields.RichTextField()),
                ('mark_as_read', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterWiseModelset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelset_title', models.CharField(help_text='Give a name to it', max_length=75)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapters')),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('image', models.ImageField(default='/courses/level1.jpg', upload_to='syllabus_image')),
                ('created_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', ckeditor.fields.RichTextField(null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.subjects')),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_statement', ckeditor.fields.RichTextField()),
                ('choice_1', ckeditor.fields.RichTextField()),
                ('choice_2', ckeditor.fields.RichTextField()),
                ('choice_3', ckeditor.fields.RichTextField()),
                ('choice_4', ckeditor.fields.RichTextField()),
                ('answer', models.CharField(choices=[('option1', 'option1'), ('option2', 'option2'), ('option3', 'option3'), ('option4', 'option4')], default='option1', max_length=75)),
                ('explanation', ckeditor.fields.RichTextField(blank=True)),
                ('modelset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.chapterwisemodelset')),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.units'),
        ),
    ]
