# Generated by Django 4.0.1 on 2022-04-01 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapters',
            name='read_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='image',
            field=models.ImageField(default='/courses/level1.jpg', upload_to='subject_image'),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(help_text='Enter the unit name in the format: Unit -1 : Bacteriology', max_length=75),
        ),
    ]
