# Generated by Django 4.0.1 on 2022-04-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_chapters_read_users_usersreadchapters'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersreadchapters',
            name='chapter_name',
            field=models.CharField(default='Default', max_length=255),
        ),
    ]
