# Generated by Django 4.0.1 on 2022-04-04 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_usersreadchapters_chapter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersreadchapters',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.units'),
            preserve_default=False,
        ),
    ]
