# Generated by Django 4.0.1 on 2022-04-05 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_email_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0005_coursegroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('allow_students', models.BooleanField(default=True)),
                ('social_auth_users', models.ManyToManyField(blank=True, to='account.EmailAddress')),
                ('subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.subjects')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chapters',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.subjects'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CourseGroup',
        ),
    ]
