# Generated by Django 4.0.1 on 2022-04-05 11:22

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_subjects_description_alter_units_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapters',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
