# Generated by Django 4.0.1 on 2022-04-07 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_subjectgroup_chapters_subject_delete_coursegroup'),
        ('courses', '0007_alter_chapters_content_alter_subjects_description'),
    ]

    operations = [
    ]
