# Generated by Django 4.0.1 on 2022-03-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_alter_team_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisors',
            name='advisor_index',
            field=models.IntegerField(default=5, help_text='give advisor an index, advisor with highest index will be displayed first.', unique=True),
            preserve_default=False,
        ),
    ]
