# Generated by Django 4.0.1 on 2022-03-14 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_advisors_advisor_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisors',
            name='advisor_index',
            field=models.IntegerField(help_text='give advisor an index, advisor with highest index will be displayed first.'),
        ),
    ]
